analyze_intent:
  description: >
    Analyze the incoming email where the intent is not clearly identified.
    Determine if we can prepare answers based on general information.
    
    Your task is to:
    1. Identify the main topics or questions in the email, even if they're vague
    2. Assess whether general information about our products/services would adequately address the email
    3. Provide a confidence score for your assessment (0.0 to 1.0)
    
    Input:
    {email_content}
  expected_output: >
    A JSON object with three fields:
    - can_prepare_general_answer (boolean): Whether a general answer can be prepared
    - identified_topics (array of strings): List of topics identified in the email
    - confidence_score (float between 0.0 and 1.0): Your confidence in this assessment
  agent: analyzer

retrieve_information:
  description: >
    Based on the analysis results, query our API and knowledge base to retrieve
    relevant information that can help address the request.
    
    Use the identified topics to guide your search and ensure you retrieve
    comprehensive information that would help address the vague request.
    
    Analysis results:
    {analysis_results}
    
    Original email:
    {email_content}
  expected_output: >
    A comprehensive list of relevant information items retrieved from the knowledge base,
    organized by topic and relevance to the query.
  agent: knowledge_retriever

create_general_answer:
  description: >
    Create a comprehensive answer based on the general information retrieved.
    Ensure the answer addresses all identified topics and is helpful even without
    specific details from the customer.
    
    Your response should:
    1. Be friendly and professional
    2. Address the topics identified in the analysis
    3. Provide useful general information
    4. Invite further questions if needed
    
    Retrieved information:
    {retrieved_info}
    
    Analysis results:
    {analysis_results}
    
    Original email:
    {email_content}
  expected_output: >
    A JSON object with three fields:
    - summary (string): A brief summary of your response
    - detailed_response (string): The complete response to the customer
    - references (array of strings): Any references to specific information sources used
  agent: content_creator

create_email_summary:
  description: >
    Create a concise summary of the email content, capturing the essential
    points and query, especially since the intent is unclear.
    
    Your summary should:
    1. Identify the main request or question
    2. Note any specific details provided
    3. Highlight any constraints or preferences mentioned
    4. Be brief but complete (3-5 bullet points)
    
    Original email:
    {email_content}
    
    Created response (if available):
    {created_response}
  expected_output: >
    A concise but comprehensive summary of the email content in 3-5 bullet points,
    highlighting the main request, specific details, and any constraints mentioned.
  agent: summary_specialist

prepare_final_material:
  description: >
    Prepare a complete package of materials for the handling agent that includes:
    1. The original email summary
    2. The created response (if available)
    3. Reference materials and sources used
    4. Suggestions for follow-up questions or clarifications
    5. Any additional context that would help the agent understand the situation
    
    This package will be handed off to a human agent who will process the request further.
    
    Email summary:
    {email_summary}
    
    Created response (if available):
    {created_response}
    
    Retrieved information:
    {retrieved_info}
    
    Original email:
    {email_content}
  expected_output: >
    A comprehensive package containing the email summary, response (if available),
    reference materials, suggested follow-up questions, and additional context
    to help the human agent process the request effectively.
  agent: content_creator

